logging:
  file:
    name: cms-dev.log
    path: logs/
  level:
    root: info
    web: info
    org.springframework.web: debug
    com.cs.sigm: info
server:
  forward-headers-strategy: framework
  port: 8081
  servlet:
    context-path: /cms
spring:
  application:
    name: sig-cms
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dbcms
    username: admin
    password: admin
    sqlScriptEncoding: UTF-8
    hikari:
      minimum-idle: 4
      maximum-pool-size: 16
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
  devtools:
    add-properties: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
cms:
  version: 0.0.1 alpha
  production: false
   